# page table
INSERT INTO page (path, page_id, code, groovy_id, title, description, layout_id, system, html, modified, date_created, date_modified, cms_page)
VALUES
  ('/dashboard', 'com.angkorteam.mbaas.server.page.DashboardPage',
                 'com.angkorteam.mbaas.server.page.DashboardPage',
                 'com.angkorteam.mbaas.server.page.DashboardPage',
                 'Dashboard', 'Dashboard',
                 'com.angkorteam.mbaas.server.page.MBaaSLayout',
                 TRUE, '', TRUE, now(), now(), FALSE),
  ('/menu/browse', 'com.angkorteam.mbaas.server.page.menu.MenuBrowsePage',
                   'com.angkorteam.mbaas.server.page.menu.MenuBrowsePage',
                   'com.angkorteam.mbaas.server.page.menu.MenuBrowsePage',
                   'Menu Browse', 'Menu Browse',
                   'com.angkorteam.mbaas.server.page.MBaaSLayout',
                   TRUE, '', TRUE, now(), now(), FALSE),
  ('/menu/create', 'com.angkorteam.mbaas.server.page.menu.MenuCreatePage',
                   'com.angkorteam.mbaas.server.page.menu.MenuCreatePage',
                   'com.angkorteam.mbaas.server.page.menu.MenuCreatePage',
                   'Menu Create', 'Menu Create',
                   'com.angkorteam.mbaas.server.page.MBaaSLayout',
                   TRUE,  '', TRUE, now(), now(), FALSE),
  ('/menu/modify', 'com.angkorteam.mbaas.server.page.menu.MenuModifyPage',
                   'com.angkorteam.mbaas.server.page.menu.MenuModifyPage',
                   'com.angkorteam.mbaas.server.page.menu.MenuModifyPage',
                   'Menu Modify', 'Menu Modify',
                   'com.angkorteam.mbaas.server.page.MBaaSLayout',
                   TRUE, '', TRUE, now(), now(), FALSE),
  ('/menu/item/browse', 'com.angkorteam.mbaas.server.page.menuitem.MenuItemBrowsePage',
                        'com.angkorteam.mbaas.server.page.menuitem.MenuItemBrowsePage',
                        'com.angkorteam.mbaas.server.page.menuitem.MenuItemBrowsePage',
                        'MenuItem Browse', 'MenuItem Browse',
                        'com.angkorteam.mbaas.server.page.MBaaSLayout',
                        TRUE, '', TRUE, now(), now(), FALSE),
  ('/menu/item/create', 'com.angkorteam.mbaas.server.page.menuitem.MenuItemCreatePage',
                        'com.angkorteam.mbaas.server.page.menuitem.MenuItemCreatePage',
                        'com.angkorteam.mbaas.server.page.menuitem.MenuItemCreatePage',
                        'MenuItem Create', 'MenuItem Create',
                        'com.angkorteam.mbaas.server.page.MBaaSLayout',
                        TRUE, '', TRUE, now(), now(), FALSE),
  ('/menu/item/modify', 'com.angkorteam.mbaas.server.page.menuitem.MenuItemModifyPage',
                        'com.angkorteam.mbaas.server.page.menuitem.MenuItemModifyPage',
                        'com.angkorteam.mbaas.server.page.menuitem.MenuItemModifyPage',
                        'MenuItem Modify', 'MenuItem Modify',
                        'com.angkorteam.mbaas.server.page.MBaaSLayout',
                        TRUE, '', TRUE, now(), now(), FALSE),
  ('/section/browse', 'com.angkorteam.mbaas.server.page.section.SectionBrowsePage',
                      'com.angkorteam.mbaas.server.page.section.SectionBrowsePage',
                      'com.angkorteam.mbaas.server.page.section.SectionBrowsePage',
                      'Section Browse', 'Section Browse',
                      'com.angkorteam.mbaas.server.page.MBaaSLayout',
                      TRUE, '', TRUE, now(), now(), FALSE),
  ('/section/create', 'com.angkorteam.mbaas.server.page.section.SectionCreatePage',
                      'com.angkorteam.mbaas.server.page.section.SectionCreatePage',
                      'com.angkorteam.mbaas.server.page.section.SectionCreatePage',
                      'Section Create', 'Section Create',
                      'com.angkorteam.mbaas.server.page.MBaaSLayout',
                      TRUE, '', TRUE, now(), now(), FALSE),
  ('/section/modify', 'com.angkorteam.mbaas.server.page.section.SectionModifyPage',
                      'com.angkorteam.mbaas.server.page.section.SectionModifyPage',
                      'com.angkorteam.mbaas.server.page.section.SectionModifyPage',
                      'Section Modify', 'Section Modify',
                      'com.angkorteam.mbaas.server.page.MBaaSLayout',
                      TRUE, '', TRUE, now(), now(), FALSE),
  ('/layout/browse', 'com.angkorteam.mbaas.server.page.layout.LayoutBrowsePage',
                     'com.angkorteam.mbaas.server.page.layout.LayoutBrowsePage',
                     'com.angkorteam.mbaas.server.page.layout.LayoutBrowsePage',
                     'Layout Browse', 'Layout Browse',
                     'com.angkorteam.mbaas.server.page.MBaaSLayout',
                     TRUE, '', TRUE, now(), now(), FALSE),
  ('/layout/create', 'com.angkorteam.mbaas.server.page.layout.LayoutCreatePage',
                     'com.angkorteam.mbaas.server.page.layout.LayoutCreatePage',
                     'com.angkorteam.mbaas.server.page.layout.LayoutCreatePage',
                     'Layout Create', 'Layout Create',
                     'com.angkorteam.mbaas.server.page.MBaaSLayout',
                     TRUE, '', TRUE, now(), now(), FALSE),
  ('/layout/modify', 'com.angkorteam.mbaas.server.page.layout.LayoutModifyPage',
                     'com.angkorteam.mbaas.server.page.layout.LayoutModifyPage',
                     'com.angkorteam.mbaas.server.page.layout.LayoutModifyPage',
                     'Layout Modify', 'Layout Modify',
                     'com.angkorteam.mbaas.server.page.MBaaSLayout',
                     TRUE, '', TRUE, now(), now(), FALSE),
  ('/page/browse', 'com.angkorteam.mbaas.server.page.page.PageModifyPage',
                   'com.angkorteam.mbaas.server.page.page.PageModifyPage',
                   'com.angkorteam.mbaas.server.page.page.PageModifyPage',
                   'Page Modify', 'Page Modify',
                   'com.angkorteam.mbaas.server.page.MBaaSLayout',
                   TRUE, '', TRUE, now(), now(), FALSE),
  ('/page/create', 'com.angkorteam.mbaas.server.page.page.PageCreatePage',
                   'com.angkorteam.mbaas.server.page.page.PageCreatePage',
                   'com.angkorteam.mbaas.server.page.page.PageCreatePage',
                   'Page Create', 'Page Create',
                   'com.angkorteam.mbaas.server.page.MBaaSLayout',
                   TRUE, '', TRUE, now(), now(), FALSE),
  ('/page/modify', 'com.angkorteam.mbaas.server.page.page.PageBrowsePage',
                   'com.angkorteam.mbaas.server.page.page.PageBrowsePage',
                   'com.angkorteam.mbaas.server.page.page.PageBrowsePage',
                   'Page Browse', 'Page Browse',
                   'com.angkorteam.mbaas.server.page.MBaaSLayout',
                   TRUE, '', TRUE, now(), now(), FALSE),
  ('/role/browse', 'com.angkorteam.mbaas.server.page.role.RoleModifyPage',
                   'com.angkorteam.mbaas.server.page.role.RoleModifyPage',
                   'com.angkorteam.mbaas.server.page.role.RoleModifyPage',
                   'Role Modify', 'Role Modify',
                   'com.angkorteam.mbaas.server.page.MBaaSLayout',
                   TRUE, '', TRUE, now(), now(), FALSE),
  ('/role/create', 'com.angkorteam.mbaas.server.page.role.RoleCreatePage',
                   'com.angkorteam.mbaas.server.page.role.RoleCreatePage',
                   'com.angkorteam.mbaas.server.page.role.RoleCreatePage',
                   'Role Create', 'Role Create',
                   'com.angkorteam.mbaas.server.page.MBaaSLayout',
                   TRUE, '', TRUE, now(), now(), FALSE),
  ('/role/modify', 'com.angkorteam.mbaas.server.page.role.RoleBrowsePage',
                   'com.angkorteam.mbaas.server.page.role.RoleBrowsePage',
                   'com.angkorteam.mbaas.server.page.role.RoleBrowsePage',
                   'Role Browse', 'Role Browse',
                   'com.angkorteam.mbaas.server.page.MBaaSLayout',
                   TRUE, '', TRUE, now(), now(), FALSE),
  ('/collection/browse', 'com.angkorteam.mbaas.server.page.collection.CollectionBrowsePage',
                         'com.angkorteam.mbaas.server.page.collection.CollectionBrowsePage',
                         'com.angkorteam.mbaas.server.page.collection.CollectionBrowsePage',
                         'Collection Browse', 'Collection Browse',
                         'com.angkorteam.mbaas.server.page.MBaaSLayout',
                         TRUE, '', TRUE, now(), now(), FALSE),
  ('/collection/create', 'com.angkorteam.mbaas.server.page.collection.CollectionCreatePage',
                         'com.angkorteam.mbaas.server.page.collection.CollectionCreatePage',
                         'com.angkorteam.mbaas.server.page.collection.CollectionCreatePage',
                         'Collection Create', 'Collection Create',
                         'com.angkorteam.mbaas.server.page.MBaaSLayout',
                         TRUE, '', TRUE, now(), now(), FALSE),
  ('/attribute/create', 'com.angkorteam.mbaas.server.page.attribute.AttributeCreatePage',
                        'com.angkorteam.mbaas.server.page.attribute.AttributeCreatePage',
                        'com.angkorteam.mbaas.server.page.attribute.AttributeCreatePage',
                        'Attribute Create', 'Attribute Create',
                        'com.angkorteam.mbaas.server.page.MBaaSLayout',
                        TRUE, '', TRUE, now(), now(), FALSE),
  ('/attribute/browse', 'com.angkorteam.mbaas.server.page.attribute.AttributeBrowsePage',
                        'com.angkorteam.mbaas.server.page.attribute.AttributeBrowsePage',
                        'com.angkorteam.mbaas.server.page.attribute.AttributeBrowsePage',
                        'Attribute Browse', 'Attribute Browse',
                        'com.angkorteam.mbaas.server.page.MBaaSLayout',
                        TRUE, '', TRUE, now(), now(), FALSE),
  ('/document/browse', 'com.angkorteam.mbaas.server.page.document.DocumentBrowsePage',
                       'com.angkorteam.mbaas.server.page.document.DocumentBrowsePage',
                       'com.angkorteam.mbaas.server.page.document.DocumentBrowsePage',
                       'Document Browse', 'Document Browse',
                       'com.angkorteam.mbaas.server.page.MBaaSLayout',
                       TRUE, '', TRUE, now(), now(), FALSE),
  ('/document/create', 'com.angkorteam.mbaas.server.page.document.DocumentCreatePage',
                       'com.angkorteam.mbaas.server.page.document.DocumentCreatePage',
                       'com.angkorteam.mbaas.server.page.document.DocumentCreatePage',
                       'Document Create', 'Document Create',
                       'com.angkorteam.mbaas.server.page.MBaaSLayout',
                       TRUE, '', TRUE, now(), now(), FALSE),
  ('/document/modify', 'com.angkorteam.mbaas.server.page.document.DocumentModifyPage',
                       'com.angkorteam.mbaas.server.page.document.DocumentModifyPage',
                       'com.angkorteam.mbaas.server.page.document.DocumentModifyPage',
                       'Document Modify', 'Document Modify',
                       'com.angkorteam.mbaas.server.page.MBaaSLayout',
                       TRUE, '', TRUE, now(), now(), FALSE),
  ('/file/modify', 'com.angkorteam.mbaas.server.page.file.FileModifyPage',
                   'com.angkorteam.mbaas.server.page.file.FileModifyPage',
                   'com.angkorteam.mbaas.server.page.file.FileModifyPage',
                   'File Modify', 'File Modify',
                   'com.angkorteam.mbaas.server.page.MBaaSLayout',
                   TRUE, '', TRUE, now(), now(), FALSE),
  ('/file/create', 'com.angkorteam.mbaas.server.page.file.FileCreatePage',
                   'com.angkorteam.mbaas.server.page.file.FileCreatePage',
                   'com.angkorteam.mbaas.server.page.file.FileCreatePage',
                   'File Create', 'File Create',
                   'com.angkorteam.mbaas.server.page.MBaaSLayout',
                   TRUE, '', TRUE, now(), now(), FALSE),
  ('/file/browse', 'com.angkorteam.mbaas.server.page.file.FileBrowsePage',
                   'com.angkorteam.mbaas.server.page.file.FileBrowsePage',
                   'com.angkorteam.mbaas.server.page.file.FileBrowsePage',
                   'File Browse', 'File Browse',
                   'com.angkorteam.mbaas.server.page.MBaaSLayout',
                   TRUE, '', TRUE, now(), now(), FALSE),
  ('/user/browse', 'com.angkorteam.mbaas.server.page.user.UserBrowsePage',
                   'com.angkorteam.mbaas.server.page.user.UserBrowsePage',
                   'com.angkorteam.mbaas.server.page.user.UserBrowsePage',
                   'User Browse', 'User Browse',
                   'com.angkorteam.mbaas.server.page.MBaaSLayout',
                   TRUE, '', TRUE, now(), now(), FALSE),
  ('/user/create', 'com.angkorteam.mbaas.server.page.user.UserCreatePage',
                   'com.angkorteam.mbaas.server.page.user.UserCreatePage',
                   'com.angkorteam.mbaas.server.page.user.UserCreatePage',
                   'User Create', 'User Create',
                   'com.angkorteam.mbaas.server.page.MBaaSLayout',
                   TRUE, '', TRUE, now(), now(), FALSE),
  ('/user/modify', 'com.angkorteam.mbaas.server.page.user.UserModifyPage',
                   'com.angkorteam.mbaas.server.page.user.UserModifyPage',
                   'com.angkorteam.mbaas.server.page.user.UserModifyPage',
                   'User Modify', 'User Modify',
                   'com.angkorteam.mbaas.server.page.MBaaSLayout',
                   TRUE, '', TRUE, now(), now(), FALSE),
  ('/user/password', 'com.angkorteam.mbaas.server.page.user.UserPasswordPage',
                     'com.angkorteam.mbaas.server.page.user.UserPasswordPage',
                     'com.angkorteam.mbaas.server.page.user.UserPasswordPage',
                     'User Password', 'User Password',
                     'com.angkorteam.mbaas.server.page.MBaaSLayout',
                     TRUE, '', TRUE, now(), now(), FALSE),
  ('/login', 'com.angkorteam.mbaas.server.page.LoginPage',
             'com.angkorteam.mbaas.server.page.LoginPage',
             'com.angkorteam.mbaas.server.page.LoginPage',
             'Login', 'Login',
             'com.angkorteam.mbaas.server.page.MBaaSLayout',
             TRUE, '', TRUE, now(), now(), FALSE),
  ('/logout', 'com.angkorteam.mbaas.server.page.LogoutPage',
              'com.angkorteam.mbaas.server.page.LogoutPage',
              'com.angkorteam.mbaas.server.page.LogoutPage',
              'Logout', 'Logout',
              'com.angkorteam.mbaas.server.page.MBaaSLayout',
              TRUE, '', TRUE, now(), now(), FALSE),
  ('/rest/browse', 'com.angkorteam.mbaas.server.page.rest.RestBrowsePage',
                   'com.angkorteam.mbaas.server.page.rest.RestBrowsePage',
                   'com.angkorteam.mbaas.server.page.rest.RestBrowsePage',
                   'Rest Browse', 'Rest Browse',
                   'com.angkorteam.mbaas.server.page.MBaaSLayout',
                   TRUE, '', TRUE, now(), now(), FALSE),
  ('/rest/create', 'com.angkorteam.mbaas.server.page.rest.RestCreatePage',
                   'com.angkorteam.mbaas.server.page.rest.RestCreatePage',
                   'com.angkorteam.mbaas.server.page.rest.RestCreatePage',
                   'Rest Create', 'Rest Create',
                   'com.angkorteam.mbaas.server.page.MBaaSLayout',
                   TRUE, '', TRUE, now(), now(), FALSE),
  ('/rest/modify', 'com.angkorteam.mbaas.server.page.rest.RestModifyPage',
                   'com.angkorteam.mbaas.server.page.rest.RestModifyPage',
                   'com.angkorteam.mbaas.server.page.rest.RestModifyPage',
                   'Rest Modify', 'Rest Modify',
                   'com.angkorteam.mbaas.server.page.MBaaSLayout',
                   TRUE, '', TRUE, now(), now(), FALSE);

