# groovy table

INSERT INTO groovy (groovy_id, java_class, script, system)
VALUES
  ('com.angkorteam.mbaas.server.page.DashboardPage',
   'com.angkorteam.mbaas.server.page.DashboardPage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.menu.MenuBrowsePage',
   'com.angkorteam.mbaas.server.page.menu.MenuBrowsePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.menu.MenuCreatePage',
   'com.angkorteam.mbaas.server.page.menu.MenuCreatePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.menu.MenuModifyPage',
   'com.angkorteam.mbaas.server.page.menu.MenuModifyPage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.menuitem.MenuItemBrowsePage',
   'com.angkorteam.mbaas.server.page.menuitem.MenuItemBrowsePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.menuitem.MenuItemCreatePage',
   'com.angkorteam.mbaas.server.page.menuitem.MenuItemCreatePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.menuitem.MenuItemModifyPage',
   'com.angkorteam.mbaas.server.page.menuitem.MenuItemModifyPage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.section.SectionBrowsePage',
   'com.angkorteam.mbaas.server.page.section.SectionBrowsePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.section.SectionCreatePage',
   'com.angkorteam.mbaas.server.page.section.SectionCreatePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.section.SectionModifyPage',
   'com.angkorteam.mbaas.server.page.section.SectionModifyPage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.layout.LayoutBrowsePage',
   'com.angkorteam.mbaas.server.page.layout.LayoutBrowsePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.layout.LayoutCreatePage',
   'com.angkorteam.mbaas.server.page.layout.LayoutCreatePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.layout.LayoutModifyPage',
   'com.angkorteam.mbaas.server.page.layout.LayoutModifyPage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.page.PageModifyPage',
   'com.angkorteam.mbaas.server.page.page.PageModifyPage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.page.PageCreatePage',
   'com.angkorteam.mbaas.server.page.page.PageCreatePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.page.PageBrowsePage',
   'com.angkorteam.mbaas.server.page.page.PageBrowsePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.page.RoleModifyPage',
   'com.angkorteam.mbaas.server.page.page.RoleModifyPage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.role.RoleCreatePage',
   'com.angkorteam.mbaas.server.page.role.RoleCreatePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.role.RoleBrowsePage',
   'com.angkorteam.mbaas.server.page.role.RoleBrowsePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.collection.CollectionBrowsePage',
   'com.angkorteam.mbaas.server.page.collection.CollectionBrowsePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.collection.CollectionCreatePage',
   'com.angkorteam.mbaas.server.page.collection.CollectionCreatePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.attribute.AttributeCreatePage',
   'com.angkorteam.mbaas.server.page.attribute.AttributeCreatePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.attribute.AttributeBrowsePage',
   'com.angkorteam.mbaas.server.page.attribute.AttributeBrowsePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.document.DocumentBrowsePage',
   'com.angkorteam.mbaas.server.page.document.DocumentBrowsePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.document.DocumentCreatePage',
   'com.angkorteam.mbaas.server.page.document.DocumentCreatePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.document.DocumentModifyPage',
   'com.angkorteam.mbaas.server.page.document.DocumentModifyPage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.file.FileModifyPage',
   'com.angkorteam.mbaas.server.page.file.FileModifyPage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.file.FileCreatePage',
   'com.angkorteam.mbaas.server.page.file.FileCreatePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.file.FileBrowsePage',
   'com.angkorteam.mbaas.server.page.file.FileBrowsePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.user.UserBrowsePage',
   'com.angkorteam.mbaas.server.page.user.UserBrowsePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.user.UserCreatePage',
   'com.angkorteam.mbaas.server.page.user.UserCreatePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.user.UserModifyPage',
   'com.angkorteam.mbaas.server.page.user.UserModifyPage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.user.UserPasswordPage',
   'com.angkorteam.mbaas.server.page.user.UserPasswordPage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.LoginPage',
   'com.angkorteam.mbaas.server.page.LoginPage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.LogoutPage',
   'com.angkorteam.mbaas.server.page.LogoutPage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.rest.RestBrowsePage',
   'com.angkorteam.mbaas.server.page.rest.RestBrowsePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.rest.RestCreatePage',
   'com.angkorteam.mbaas.server.page.rest.RestCreatePage', '', TRUE),
  ('com.angkorteam.mbaas.server.page.rest.RestModifyPage',
   'com.angkorteam.mbaas.server.page.rest.RestModifyPage', '', TRUE);

