package com.angkorteam.mbaas.server;

import org.apache.commons.io.FileUtils;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by Khauv Socheat on 4/17/2016.
 */
public abstract class MBaaS {

    public static final List<String> COUNTRIES = new ArrayList<>();

    static {
        COUNTRIES.add("Afghanistan");
        COUNTRIES.add("Albania");
        COUNTRIES.add("Algeria");
        COUNTRIES.add("American Samoa");
        COUNTRIES.add("Andorra");
        COUNTRIES.add("Angola");
        COUNTRIES.add("Anguilla");
        COUNTRIES.add("Antarctica");
        COUNTRIES.add("Antigua And Barbuda");
        COUNTRIES.add("Argentina");
        COUNTRIES.add("Armenia");
        COUNTRIES.add("Aruba");
        COUNTRIES.add("Australia");
        COUNTRIES.add("Austria");
        COUNTRIES.add("Azerbaijan");
        COUNTRIES.add("ABahamas");
        COUNTRIES.add("ABahrain");
        COUNTRIES.add("ABangladesh");
        COUNTRIES.add("ABarbados");
        COUNTRIES.add("ABelarus");
        COUNTRIES.add("ABelgium");
        COUNTRIES.add("ABelize");
        COUNTRIES.add("ABenin");
        COUNTRIES.add("ABermuda");
        COUNTRIES.add("ABhutan");
        COUNTRIES.add("ABolivia");
        COUNTRIES.add("ABosnia And Herzegovina");
        COUNTRIES.add("ABotswana");
        COUNTRIES.add("ABouvet Island");
        COUNTRIES.add("ABrazil");
        COUNTRIES.add("ABritish Indian Ocean Territory");
        COUNTRIES.add("ABrunei Darussalam");
        COUNTRIES.add("ABulgaria");
        COUNTRIES.add("ABurkina Faso");
        COUNTRIES.add("ABurundi");
        COUNTRIES.add("ACambodia");
        COUNTRIES.add("ACameroon");
        COUNTRIES.add("ACanada");
        COUNTRIES.add("ACape Verde");
        COUNTRIES.add("ACayman Islands");
        COUNTRIES.add("ACentral African Republic");
        COUNTRIES.add("AChad");
        COUNTRIES.add("AChile");
        COUNTRIES.add("AChina");
        COUNTRIES.add("AChristmas Island");
        COUNTRIES.add("ACocos (keeling) Islands");
        COUNTRIES.add("AColombia");
        COUNTRIES.add("AComoros");
        COUNTRIES.add("ACongo");
        COUNTRIES.add("ACongo, The Democratic Republic Of The");
        COUNTRIES.add("Cook Islands");
        COUNTRIES.add("Costa Rica");
        COUNTRIES.add("Cote D'ivoire");
        COUNTRIES.add("Croatia");
        COUNTRIES.add("Cuba");
        COUNTRIES.add("Cyprus");
        COUNTRIES.add("Czech Republic");
        COUNTRIES.add("Denmark");
        COUNTRIES.add("Djibouti");
        COUNTRIES.add("Dominica");
        COUNTRIES.add("Dominican Republic");
        COUNTRIES.add("East Timor");
        COUNTRIES.add("Ecuador");
        COUNTRIES.add("Egypt");
        COUNTRIES.add("El Salvador");
        COUNTRIES.add("Equatorial Guinea");
        COUNTRIES.add("Eritrea");
        COUNTRIES.add("Estonia");
        COUNTRIES.add("Ethiopia");
        COUNTRIES.add("Falkland Islands (malvinas)");
        COUNTRIES.add("Faroe Islands");
        COUNTRIES.add("Fiji");
        COUNTRIES.add("Finland");
        COUNTRIES.add("France");
        COUNTRIES.add("French Guiana");
        COUNTRIES.add("French Polynesia");
        COUNTRIES.add("French Southern Territories");
        COUNTRIES.add("Gabon");
        COUNTRIES.add("Gambia");
        COUNTRIES.add("Georgia");
        COUNTRIES.add("Germany");
        COUNTRIES.add("Ghana");
        COUNTRIES.add("Gibraltar");
        COUNTRIES.add("Greece");
        COUNTRIES.add("Greenland");
        COUNTRIES.add("Grenada");
        COUNTRIES.add("Guadeloupe");
        COUNTRIES.add("Guam");
        COUNTRIES.add("Guatemala");
        COUNTRIES.add("Guinea");
        COUNTRIES.add("Guinea-bissau");
        COUNTRIES.add("Guyana");
        COUNTRIES.add("Haiti");
        COUNTRIES.add("Heard Island And Mcdonald Islands");
        COUNTRIES.add("Holy See (vatican City State)");
        COUNTRIES.add("Honduras");
        COUNTRIES.add("Hong Kong");
        COUNTRIES.add("Hungary");
        COUNTRIES.add("Iceland");
        COUNTRIES.add("India");
        COUNTRIES.add("Indonesia");
        COUNTRIES.add("Iran, Islamic Republic Of");
        COUNTRIES.add("Iraq");
        COUNTRIES.add("Ireland");
        COUNTRIES.add("Israel");
        COUNTRIES.add("Italy");
        COUNTRIES.add("Jamaica");
        COUNTRIES.add("Japan");
        COUNTRIES.add("Jordan");
        COUNTRIES.add("Kazakstan");
        COUNTRIES.add("Kenya");
        COUNTRIES.add("Kiribati");
        COUNTRIES.add("Korea, Democratic People's Republic Of");
        COUNTRIES.add("Korea, Republic Of");
        COUNTRIES.add("Kosovo");
        COUNTRIES.add("Kuwait");
        COUNTRIES.add("Kyrgyzstan");
        COUNTRIES.add("Lao People's Democratic Republic");
        COUNTRIES.add("Latvia");
        COUNTRIES.add("Lebanon");
        COUNTRIES.add("Lesotho");
        COUNTRIES.add("Liberia");
        COUNTRIES.add("Libyan Arab Jamahiriya");
        COUNTRIES.add("Liechtenstein");
        COUNTRIES.add("Lithuania");
        COUNTRIES.add("Luxembourg");
        COUNTRIES.add("Macau");
        COUNTRIES.add("Macedonia, The Former Yugoslav Republic Of");
        COUNTRIES.add("Madagascar");
        COUNTRIES.add("Malawi");
        COUNTRIES.add("Malaysia");
        COUNTRIES.add("Maldives");
        COUNTRIES.add("Mali");
        COUNTRIES.add("Malta");
        COUNTRIES.add("Marshall Islands");
        COUNTRIES.add("Martinique");
        COUNTRIES.add("Mauritania");
        COUNTRIES.add("Mauritius");
        COUNTRIES.add("Mayotte");
        COUNTRIES.add("Mexico");
        COUNTRIES.add("Micronesia, Federated States Of");
        COUNTRIES.add("Moldova, Republic Of");
        COUNTRIES.add("Monaco");
        COUNTRIES.add("Mongolia");
        COUNTRIES.add("Montserrat");
        COUNTRIES.add("Montenegro");
        COUNTRIES.add("Morocco");
        COUNTRIES.add("Mozambique");
        COUNTRIES.add("Myanmar");
        COUNTRIES.add("Namibia");
        COUNTRIES.add("Nauru");
        COUNTRIES.add("Nepal");
        COUNTRIES.add("Netherlands");
        COUNTRIES.add("Netherlands Antilles");
        COUNTRIES.add("New Caledonia");
        COUNTRIES.add("New Zealand");
        COUNTRIES.add("Nicaragua");
        COUNTRIES.add("Niger");
        COUNTRIES.add("Nigeria");
        COUNTRIES.add("Niue");
        COUNTRIES.add("Norfolk Island");
        COUNTRIES.add("Northern Mariana Islands");
        COUNTRIES.add("Norway");
        COUNTRIES.add("Oman");
        COUNTRIES.add("Pakistan");
        COUNTRIES.add("Palau");
        COUNTRIES.add("Palestinian Territory, Occupied");
        COUNTRIES.add("Panama");
        COUNTRIES.add("Papua New Guinea");
        COUNTRIES.add("Paraguay");
        COUNTRIES.add("Peru");
        COUNTRIES.add("Philippines");
        COUNTRIES.add("Pitcairn");
        COUNTRIES.add("Poland");
        COUNTRIES.add("Portugal");
        COUNTRIES.add("Puerto Rico");
        COUNTRIES.add("Qatar");
        COUNTRIES.add("Reunion");
        COUNTRIES.add("Romania");
        COUNTRIES.add("Russian Federation");
        COUNTRIES.add("Rwanda");
        COUNTRIES.add("Saint Helena");
        COUNTRIES.add("Saint Kitts And Nevis");
        COUNTRIES.add("Saint Lucia");
        COUNTRIES.add("Saint Pierre And Miquelon");
        COUNTRIES.add("Saint Vincent And The Grenadines");
        COUNTRIES.add("Samoa");
        COUNTRIES.add("San Marino");
        COUNTRIES.add("Sao Tome And Principe");
        COUNTRIES.add("Saudi Arabia");
        COUNTRIES.add("Senegal");
        COUNTRIES.add("Serbia");
        COUNTRIES.add("Seychelles");
        COUNTRIES.add("Sierra Leone");
        COUNTRIES.add("Singapore");
        COUNTRIES.add("Slovakia");
        COUNTRIES.add("Slovenia");
        COUNTRIES.add("Solomon Islands");
        COUNTRIES.add("Somalia");
        COUNTRIES.add("South Africa");
        COUNTRIES.add("South Georgia And The South Sandwich Islands");
        COUNTRIES.add("Spain");
        COUNTRIES.add("Sri Lanka");
        COUNTRIES.add("Sudan");
        COUNTRIES.add("Suriname");
        COUNTRIES.add("Svalbard And Jan Mayen");
        COUNTRIES.add("Swaziland");
        COUNTRIES.add("Sweden");
        COUNTRIES.add("Switzerland");
        COUNTRIES.add("Syrian Arab Republic");
        COUNTRIES.add("Taiwan, Province Of China");
        COUNTRIES.add("Tajikistan");
        COUNTRIES.add("Tanzania, United Republic Of");
        COUNTRIES.add("Thailand");
        COUNTRIES.add("Togo");
        COUNTRIES.add("Tokelau");
        COUNTRIES.add("Tonga");
        COUNTRIES.add("Trinidad And Tobago");
        COUNTRIES.add("Tunisia");
        COUNTRIES.add("Turkey");
        COUNTRIES.add("Turkmenistan");
        COUNTRIES.add("Turks And Caicos Islands");
        COUNTRIES.add("Tuvalu");
        COUNTRIES.add("Uganda");
        COUNTRIES.add("Ukraine");
        COUNTRIES.add("United Arab Emirates");
        COUNTRIES.add("United Kingdom");
        COUNTRIES.add("United States");
        COUNTRIES.add("United States Minor Outlying Islands");
        COUNTRIES.add("Uruguay");
        COUNTRIES.add("Uzbekistan");
        COUNTRIES.add("Vanuatu");
        COUNTRIES.add("Venezuela");
        COUNTRIES.add("Viet Nam");
        COUNTRIES.add("Virgin Islands, British");
        COUNTRIES.add("Virgin Islands, U.s.");
        COUNTRIES.add("Wallis And Futuna");
        COUNTRIES.add("Western Sahara");
        COUNTRIES.add("Yemen");
        COUNTRIES.add("Zambia");
        COUNTRIES.add("Zimbabwe");
    }

}
